import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/section/Navbar";
import Footer from "@/components/section/Footer";
import { GlobalProvider } from "@/components/contexts/GlobalProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalProvider>
          <Navbar />
          {children}
          <Footer />
        </GlobalProvider>
      </body>
    </html>
  );
}
